#!/usr/bin/env python3
"""GROWW Weekly Review Pulse - dashboard data builder.

Reads data/reviews_all.csv, classifies every review, computes theme stats and
top-3 quotes, assembles a deterministic note PREVIEW (no LLM), and writes
web/dashboard_data.json for the static dashboard. The real LLM note + email
are generated by the Apps Script step; this preview exists so the local web
app can be exercised without a Gemini key.
"""

import argparse
import csv
import datetime
import json
import sys

from pulse_shared import THEMES, THEME_NAMES, PII_PROBE, rule_classify, exact_quote, theme_stats, sentence, coverage_footer

WORD_LIMIT = 250


def quote_for_theme(theme_rows):
    pool = [r for r in theme_rows if str(r.get("text") or "").strip()]
    pool.sort(key=lambda r: int(r["rating"]))
    if not pool:
        return {"quote": "", "rating": ""}
    q = exact_quote(pool[0]["text"], pool[0]["title"])
    if not q:
        return {"quote": "", "rating": ""}
    src = pool[0]["text"] or pool[0]["title"] or ""
    if q not in src:
        return {"quote": "", "rating": ""}
    return {"quote": q, "rating": pool[0]["rating"]}


def build_note_preview(top3, unclassified, total):
    if not top3:
        return "WEEKLY REVIEW PULSE - GROWW\nNo qualifying themes this week."
    footer = coverage_footer(total, unclassified)
    body_max = WORD_LIMIT - len(footer.split())
    parts = [
        "WEEKLY REVIEW PULSE - GROWW",
        "Preview: " + ", ".join(t["theme"] for t in top3) +
        " dominate the week's signal; ranked themes below.",
    ]
    for t in top3:
        parts.append(
            f"{t['rank']}. {t['theme']} ({t['count']} reviews, ~{t['avg_rating']}/5): "
            f"\"{t['top_quote']}\" - lowest-rated review in this theme. "
            f"Action: {sentence('prioritise investigation into ' + t['theme'] + ' this week')}"
        )
    note = "\n".join(parts)
    while len(note.split()) > body_max and len(parts) > 2:
        tail = parts[-1].split(" ")
        tail = tail[:-1]
        parts[-1] = " ".join(tail)
        note = "\n".join(parts)
    return note + "\n" + footer


def build_actions_preview(top3):
    return [f"Prioritise investigation into {t['theme']} this week." for t in top3]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default="data/reviews_all.csv")
    ap.add_argument("--out", default="web/dashboard_data.json")
    args = ap.parse_args()

    with open(args.inp, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    for r in rows:
        r["_theme"] = rule_classify(r.get("title"), r.get("text"))
        r["rating"] = int(r["rating"])

    stats, unclassified = theme_stats(rows)
    by_theme = {}
    for r in rows:
        by_theme.setdefault(r["_theme"], []).append(r)

    enriched = []
    for s in stats:
        q = quote_for_theme(by_theme.get(s["theme"], []))
        s["top_quote"] = q["quote"]
        s["top_quote_rating"] = q["rating"]
        enriched.append(s)

    top3 = [s for s in enriched if s["rank"] <= 3 and s["count"] > 0 and s["top_quote"]][:3]
    note = build_note_preview(top3, unclassified, len(rows))
    actions = build_actions_preview(top3)

    platforms = {}
    for r in rows:
        platforms[r["platform"]] = platforms.get(r["platform"], 0) + 1
    dates = sorted({r["date"] for r in rows if r["date"]})
    avg = sum(r["rating"] for r in rows) / len(rows)

    payload = {
        "app": "GROWW",
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "source_count": len(rows),
        "source_breakdown": platforms,
        "date_range": {"min": dates[0] if dates else "", "max": dates[-1] if dates else ""},
        "avg_rating": round(avg, 2),
        "unclassified": unclassified,
        "coverage": {
            "total": len(rows),
            "classified": len(rows) - unclassified,
            "unclassified": unclassified,
        },
        "legend": THEME_NAMES,
        "themes": enriched,
        "top3": top3,
        "note": {
            "text": note,
            "word_count": len(note.split()),
            "is_preview": True,
            "note_limitation": "Deterministic preview — click Generate weekly note for the Gemini note, Generate email draft for the digest email.",
        },
        "actions": actions,
        "reviews": [
            {
                "date": r["date"],
                "platform": r["platform"],
                "rating": r["rating"],
                "title": r.get("title") or "",
                "text": r.get("text") or "",
                "theme": r["_theme"],
            }
            for r in rows
        ],
        "checks": {
            "columns": ["rating", "title", "text", "date", "platform"],
            "ratings_1_5": all(r["rating"] in (1, 2, 3, 4, 5) for r in rows),
            "pii_hits": sum(
                1 for r in rows if PII_PROBE.search(f"{r.get('title','')} {r.get('text','')}")
            ),
            "theme_count_within_legend": len(enriched) <= len(THEME_NAMES),
            "note_word_limit": len(note.split()) <= WORD_LIMIT,
        },
    }

    import os
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)

    print(f"wrote {args.out}")
    print(f"reviews={len(rows)} avg={payload['avg_rating']} themes={len(enriched)} top3=" +
          ", ".join(f"{t['theme']} ({t['priority_score']})" for t in top3))
    print(f"note preview: {payload['note']['word_count']} words (limit {WORD_LIMIT})")


if __name__ == "__main__":
    sys.exit(main())